[package]
name = "robokots-rust"
version = "0.0.1"
edition = "2021"

[lib]
name = "robokots_rust"
crate-type = ["cdylib", "rlib"]

[features]
default = ["python"]
python = ["dep:numpy", "dep:pyo3"]

[dependencies]
numpy = { version = "0.23", optional = true }
pyo3 = { version = "0.23", features = ["extension-module"], optional = true }

[profile.release]
codegen-units = 1
lto = "thin"
